#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VPNSPACE_SH="${VPNSPACE_SH:-${SCRIPT_DIR}/vpnspace.sh}"

NS_NAME="${VPN_NAMESPACE:-vpnspace}"
DOCKERD_BIN="${DOCKERD_BIN:-/usr/bin/dockerd}"
SOCK_PATH="${VPN_DOCKER_SOCK:-/run/docker-vpnspace.sock}"
PID_FILE="${VPN_DOCKER_PIDFILE:-/run/docker-vpnspace.pid}"
DATA_ROOT="${VPN_DOCKER_DATA_ROOT:-/var/lib/docker-vpnspace}"
EXEC_ROOT="${VPN_DOCKER_EXEC_ROOT:-/var/run/docker-vpnspace}"
BIP="${VPN_DOCKER_BIP:-172.30.0.1/24}"
CGROUP_DRIVER="${VPN_DOCKER_CGROUP_DRIVER:-systemd}"
AUTO_EXPORT="${VPN_DOCKER_AUTO_EXPORT:-1}"
PROFILE_SNIPPET="${VPN_DOCKER_PROFILE_SNIPPET:-/etc/profile.d/abb-docker-host.sh}"
SOCK_URI="unix://${SOCK_PATH}"

require_root() {
  if [[ "${EUID}" -ne 0 ]]; then
    exec sudo -E "$0" "$@"
  fi
}

ensure_helpers() {
  [[ -x "${VPNSPACE_SH}" ]] || { echo "vpnspace.sh not found at ${VPNSPACE_SH}" >&2; exit 1; }
  command -v "${DOCKERD_BIN}" >/dev/null || { echo "dockerd not found at ${DOCKERD_BIN}" >&2; exit 1; }
}

ensure_namespace() {
  if ! ip netns list | grep -q "^${NS_NAME}\b"; then
    echo "Namespace ${NS_NAME} missing. Run vpnspace.sh setup first." >&2
    exit 1
  fi
}

ensure_cgroup_mounts() {
  local mount_script='
set -e
mkdir -p /sys/fs/cgroup
if ! mountpoint -q /sys/fs/cgroup; then
  if ! mount -t cgroup2 none /sys/fs/cgroup 2>/dev/null; then
    mount -t tmpfs cgroup_root /sys/fs/cgroup
    for ctrl in blkio cpu cpuacct cpuset devices freezer hugetlb memory net_cls net_prio perf_event pids rdma; do
      mkdir -p "/sys/fs/cgroup/${ctrl}"
      mount -t cgroup -o "${ctrl}" cgroup "/sys/fs/cgroup/${ctrl}" 2>/dev/null || true
    done
  fi
fi
'
  if ! ip netns exec "${NS_NAME}" mountpoint -q /sys/fs/cgroup 2>/dev/null; then
    ip netns exec "${NS_NAME}" /bin/sh -c "${mount_script}" || {
      echo "Warning: failed to mount cgroups inside ${NS_NAME}; dockerd may fail." >&2
    }
  fi
}

install_profile_snippet() {
  [[ "${AUTO_EXPORT}" == "0" ]] && return
  install -d -m 0755 "$(dirname "${PROFILE_SNIPPET}")"
  cat <<EOF > "${PROFILE_SNIPPET}"
# shellcheck shell=sh
# Auto-generated by vpnspace-dockerd.sh; prefer vpnspace dockerd when socket exists.
if [ -z "\${ABB_NO_VPNSPACE:-}" ] && [ -S "${SOCK_PATH}" ]; then
  export DOCKER_HOST="${SOCK_URI}"
fi
EOF
  chmod 0644 "${PROFILE_SNIPPET}"
}

remove_profile_snippet() {
  [[ -f "${PROFILE_SNIPPET}" ]] && rm -f "${PROFILE_SNIPPET}"
}

start_dockerd() {
  ensure_namespace
  ensure_cgroup_mounts
  if [[ -f "${PID_FILE}" ]] && kill -0 "$(cat "${PID_FILE}")" 2>/dev/null; then
    echo "dockerd already running inside ${NS_NAME} (pid $(cat "${PID_FILE}"))." >&2
    exit 0
  fi
  mkdir -p "$(dirname "${SOCK_PATH}")" "${DATA_ROOT}" "${EXEC_ROOT}"
  ip netns exec "${NS_NAME}" "${DOCKERD_BIN}" \
    --host="unix://${SOCK_PATH}" \
    --data-root="${DATA_ROOT}" \
    --exec-root="${EXEC_ROOT}" \
    --pidfile="${PID_FILE}" \
    --bip="${BIP}" \
    --exec-opt "native.cgroupdriver=${CGROUP_DRIVER}" \
    --iptables=false \
    --ip-masq=false &
  local pid=$!
  sleep 2
  if ! kill -0 "${pid}" 2>/dev/null; then
    echo "Failed to start dockerd inside ${NS_NAME}." >&2
    exit 1
  fi
  echo "${pid}" > "${PID_FILE}"
  install_profile_snippet
  echo "dockerd started in namespace ${NS_NAME} (socket ${SOCK_PATH})."
  echo "New shells auto-export DOCKER_HOST=${SOCK_URI} (set ABB_NO_VPNSPACE=1 to opt out)."
}

stop_dockerd() {
  if [[ -f "${PID_FILE}" ]]; then
    local pid
    pid="$(cat "${PID_FILE}")"
    if kill -0 "${pid}" 2>/dev/null; then
      kill "${pid}"
      wait "${pid}" 2>/dev/null || true
    fi
    rm -f "${PID_FILE}"
  fi
  rm -f "${SOCK_PATH}"
  remove_profile_snippet
  echo "dockerd in ${NS_NAME} stopped."
}

status_dockerd() {
  if [[ -f "${PID_FILE}" ]] && kill -0 "$(cat "${PID_FILE}")" 2>/dev/null; then
    echo "dockerd running (pid $(cat "${PID_FILE}")), socket ${SOCK_PATH}"
  else
    echo "dockerd is not running inside ${NS_NAME}"
    return 1
  fi
}

print_usage() {
  cat <<'EOF'
Usage: vpnspace-dockerd.sh <start|stop|status>

Starts a dedicated dockerd instance inside the vpnspace namespace.
Point DOCKER_HOST=unix:///run/docker-vpnspace.sock when running docker/compose
commands to ensure containers use the ProtonVPN namespace.
EOF
}

main() {
  require_root "$@"
  ensure_helpers
  local cmd="${1:-}"
  case "${cmd}" in
    start) start_dockerd ;;
    stop) stop_dockerd ;;
    status) status_dockerd ;;
    *) print_usage; exit 1 ;;
  esac
}

main "$@"
